POST http://localhost:8000
Content-Type: application/json

{
  "name": "Yoghurt",
  "calories": 60,
  "price": 12
}

###

GET http://localhost:8000

###

GET http://localhost:8000/product/5
// Get product with specific id v2

###

DELETE http://localhost:8000

###

PUT http://localhost:8000
